### ISSUE TITLE
Support load balancing through the client AKA multiple EMQX server list

### ISSUE THREAD

**Issue by ncg81** [emqx/qmqtt#189]
Rationale:

LBs  are a common server hosting solution. The lack of clustering support in this client suggests that the developers expect EMQX clusters to be deployed behind some sort of load balancer.

However, you wouldn't believe the weird LB offerings some hosting providers offer. For example, they would support a unique setup, say a LB @ 100 Mbps when their lowest instance (EMQX node) bandwidth would support 300 Mbps.

It is not optimal to deploy an EMQX cluster behind such a LB. Say one deploys 3 EMQX nodes @ 300 Mbps, that is to say a 900 Mbps aggregated bandwidth for the entire EMQX cluster. And yet, the best one can do in terms of load balancing is 1 (one) 100 Mbps LB. Clearly such a LB does actually "load balance" anything, it merely bottlenecks the EMQX cluster in terms of bandwidth.

Alternatives?

1. DNS load balancing. Not optimal due to obscene DNS caching by multiple third parties (such as ISPs). Not to mention unnecessarily complicating infrastructure requirements.
2. Round robin load balancing performed at client level (**qmqtt**). Easily solves the inconveniences listed above.

As a developer seriously considering EMQX ad the broker of choice, I would rather spend money to upgrade to EMQX Enterprise when I need to scale than paying for load blanacers or for the requirements of complicate infrastructure setups due to missing functionality in EMQX client libraries.

Hence, please add server list load balancing (round robin would suffice) support for **qmqtt**.

**Comment by mwallnoefer** [comment]
What regards to new features in respect to mqtt 5 please consider issue #188 .

In respect to load balancing I guess that this is not something easy to add since it would require some restructuring. Since qmqtt was moved to maintenance mode by decision of the developer team we won't provide new functionality. If you still would like to propose us some patch we can have a discussion on it but without any acceptance guarantee (but please be aware to not break something and add or extend the unit tests).
 
That said I would kindly invite you to have a look at the Qt Mqtt project https://doc.qt.io/QtMQTT/index.html (code repo https://code.qt.io/cgit/qt/qtmqtt.git/) which for sure welcomes questions like this to a greater extent.
