### ISSUE TITLE
Small improvement in handling SSL errors 

### ISSUE THREAD

**Issue by sergey-sukiyazov** [emqx/qmqtt#193]
Hi!

I faced with the problem on attempt to connect to mosquitto broker via SSL. It happens because Qt < 5.13 has a bug with populating of IP addresses in Subject "Alternative Name" in a Certificates, see [this](https://forum.qt.io/topic/96458/qsslsocket-the-field-ip-address-is-not-considered-in-subject-alternative-name-in-a-certificate) and [this](https://bugreports.qt.io/browse/QTBUG-71828). So, there is no way to connect to mosquitto broker via SSL if you use only IP addreses (inside loacl network) and Qt < 5.13. Ths can be related to [this](https://github.com/emqx/qmqtt/issues/190).

So, i made small changes in the handling of SSL errors on `QSslSocket`, to be able to ignore `QSslError::HostNameMismatch` errors if the `QSslConfiguration::setPeerVerifyMode(QSslSocket::VerifyNone)` is set for `QSslSocket`, ie:
```
QSslConfiguration sslConfig = QSslConfiguration::defaultConfiguration();
sslConfig.setCaCertificates({<your CA cert>});
sslConfig.setLocalCertificate(<your cert>);
sslConfig.setPrivateKey(<your key>);
sslConfig.setPeerVerifyMode(QSslSocket::VerifyNone);

MQTT::Client *client = new QMQTT::Client("<your IP address>", <your port>, sslConfig);
```
in this case it's possible to configure client to ignore checking of peer host name, like `mosquitto_pup/mosquitto_sub` does.

The patch attached (inside the ZIP).

[0001-fix-handling-ssl-error-host-name-mismatch.patch.zip](https://github.com/emqx/qmqtt/files/3933578/0001-fix-handling-ssl-error-host-name-mismatch.patch.zip)

**Comment by mwallnoefer** [comment]
@ejvr Please review the patch!

@sergey-sukiyazov Could you open us a pull request, so we may merge it from the GitHub frontend?

**Comment by ejvr** [comment]
The patch is looking good. In my opinion, you throw away most of the security SSL can offer if you use the `VerifyNone` option, so I would not advice anyone to use it. One problem though: the documentation of states that `QSslSocket::ignoreSslErrors()` should be called to ignore errors during the socket's handshake. The example provided for `QSslSocket::ignoreSslErrors(const QList<QSslError> &errors)` indicates that that function is intended to be used before connecting. So that implies that within `QMQTT::SslSocket::sslErrors` the function `QSslSocket::ignoreSslErrors()` should be called instead of the other overload. This changes the way `sslErrors` works, because you have to go through all errors and call `ignoreSslErrors` only if you want to ignore *all* errors passed to that function.

On the other end, how many other 'tweaks' do we need to keep the SSL part of this library usable? I don't like the idea of inserting more code because of edge cases like this. Instead of that I'd like to propose an alternative:

We externalize the function that handles ssl errors. To do that we need a new signal in `QMQTT::Client` that has the same signature as `void QSslSocket::sslErrors(const QList<QSslError> &errors)`. The signal is emitted whenever the internal `QSslSocket` fires. Additionally, we add the functions `void QSslSocket::ignoreSslErrors(const QList<QSslError> &errors)` and `void QSslSocket::ignoreSslErrors()`. The former can be used to set the list of errors to be ignored before connecting the socket, the latter to ignore error during the connection set-up.

Note that `QWebSocket` uses the same mechanism to handle SSL errors.

@mwallnoefer, @sergey-sukiyazov Please let me know what you think. If you like the alternative I can provide a pull request.

**Comment by mwallnoefer** [comment]
> On the other end, how many other 'tweaks' do we need to keep the SSL part of this library usable? I don't like the idea of inserting more code because of edge cases like this. Instead of that I'd like to propose an alternative:

Good idea, @ejvr. I agree with an API extension to avoid repetitive patching, often also for little benefit in very special cases.

**Comment by sergey-sukiyazov** [comment]
Hi everybody!

> On the other end, how many other 'tweaks' do we need to keep the SSL part of this library usable? I don't like the idea of inserting more code because of edge cases like this. Instead of that I'd like to propose an alternative:

Agree that this idea is much better than what i suggested (I thought about this aloso, but decided to not do changes in the clasess specs). Thanks!

**Comment by sergey-sukiyazov** [comment]
@ejvr 
I would be good if you also add the method into `QMQTT::Client` which will return `QSslConfiguration` which is used for SSL connections, like
```
QSslConfiguration QMQTT::Client::sslConfiguration() const;
```

**Comment by mwallnoefer** [comment]
I have merged @ejvr's patch proposal.

Please tell me what to do in regard of `sslConfiguration()`.

**Comment by ejvr** [comment]
@mwallnoefer I can implement the changr and create a new pull request.

**Comment by mwallnoefer** [comment]
Okay, thanks @ejvr for the patches!
