### ISSUE TITLE
SSL connection to different hostname than "issued-to" in the broker certificate

### ISSUE THREAD

**Issue by dhoegerl** [emqx/qmqtt#198]
Hello guys!

We've observed, that the qmqtt library can only connect to a broker using SSL, if the used hostname is identical to the hostname, specified in the server certificate on broker side. This can be verified easily by running a local mosquitto with a certificate issued to some computer name, e.g. "my-pc". If we connect to the local mosquitto using "localhost" or "127.0.0.1" the qmqtt library will fail with handshake-error. However, if we use the very same name as specified in the certificate "my-pc" for connection, everything works OK.

We first thought this was standard behavior for MQTT communication, but unfortunately found out, that other clients like MQTTfx can establish the connection independent of the hostname.

Can this behavior be changed in qmqtt library or somehow avoided?

Thank you, Daniel

**Comment by mwallnoefer** [comment]
@KonstantinRitt What do you think?

**Comment by KonstantinRitt** [comment]
See QMQTT::SslSocket::connectToHost: the QSslSocket's connectToHostEncrypted() overload could take the ssl peername other than the hostname to connect to.

**Comment by dhoegerl** [comment]
What does this mean for the user of the QMQTT library like us? We simply call connectToHost() on the client object. Obviously, proven by tests with different brokers, we currently have to pass the hostname to the connectToHost() call that is also written in the server certificate on the broker.

**Comment by mwallnoefer** [comment]
I am not the expert in qmqtt's SSL part but I think @KonstantinRitt wanted to say that you have to use the following client constructor:
```
    Client(const QString& hostName,
           const quint16 port,
           const QSslConfiguration& config,
           const bool ignoreSelfSigned=false,
           QObject* parent = NULL);
```
There you will need to pass a `QSslConfiguration` configuration object where you set the option _SSL peername_ most probably to _localhost_. Please have a look at the Qt documentation for the details, it should be explained there.

**Comment by dhoegerl** [comment]
We already use this client constructor for SSL connection. However, in the [QSslConfiguration](https://doc.qt.io/qt-5/qsslconfiguration.html) object I cannot find a _peername_ property - I only find it in the QWebSocket class. Can you give me another hint, so I can give it a try?

**Comment by mwallnoefer** [comment]
Unfortunately you are right, this property may only be set at connection time on the _QSslSocket_ s _connectToHostEncrypted_ method (https://doc.qt.io/qt-5/qsslsocket.html#connectToHostEncrypted-1).

So yes, there would be some patching required, the first part in https://github.com/emqx/qmqtt/blob/master/src/mqtt/qmqtt_ssl_socket.cpp to add a new _connectToHost()_ method with the new overload, but then you are required to add it to the base class as well (_SocketInterface_).
And finally you have to repeat this for both the network and the client class, therefore it is not so immediate :thinking:.

On the other hand we are also not so keen any more to accept such changes, since in the meantime there has been developed Qt's own mqtt library. So we will also not implement Mqtt 5 and things like that.

**Comment by dhoegerl** [comment]
After your hints I played around a bit and there seems to be an easier solution:
`QSslConfiguration::setPeerVerifyMode(QSslSocket::VerifyNone)`

This makes it work like other clients and avoids the _peername_ verification.
