### ISSUE TITLE
Integrate with QT 5.15.3

### ISSUE THREAD

**Issue by Ordissimo** [emqx/qmqtt#246]
QT version :
```
QMake version 3.1
Using Qt version 5.15.3 in /usr/lib/x86_64-linux-gnu
```
Error:
```
lrelease MyProject.pro 
WARNING: Project ERROR: Unknown module(s) in QT: qmqtt
```

build and install qmqtt:
```
mkdir buildir
cd buildir
cmake ../
cmake --build .
sudo make install
```
I can't use qmqtt.
Do you have any idea what I am doing wrong?

**Comment by mwallnoefer** [comment]
@ejvr any idea?

**Comment by ejvr** [comment]
@Ordissimo I wonder what you're trying to achieve with the `lrelease` command. According to the manual it is used to create translation (maybe that's why you see the warning / error). Are you sure that's what you want?

If you just want to get your own application build, and you want to use qmake to do so, please try to compile & install qmqtt with qmake as well.

**Comment by Ordissimo** [comment]
@ejvr,
Qmake gives me the same result, the dependency check fails.
I use debian bookworm.

**Comment by ejvr** [comment]
Did you try to build & install qmqtt using qmake instead of cmake?

------- Original Message -------

**Comment by Ordissimo** [comment]
@ejr and @mwallnoefer, Thanks for your help, qmake solves the problem:

```
mkdir build
cd build
qmake ../
make
sudo make install
```
